### ISSUE TITLE
Detection using YOLOV8 & Segmentation using SAM  

### ISSUE THREAD

**Issue by AouatifZ** [akashAD98/YOLOV8_SAM#1]
Thank You for Creating this repository  that very helpful

**Comment by akashAD98** [comment]
@AouatifZ exactly im working on this part also, want to detect multiple objects, open source conttributions are welcome

**Comment by mhyeonsoo** [comment]
@akashAD98 
One more thanks here,
For now I just came up with an idea of running the sam model inference with a look with the yolo multi-class object detection result bboxes, but the latency may be the issue.
I'll also try to look for some good ideas and contribute hopefully.

BTW do you think using yolov8 detector + SAM segmentation would be better in terms of maskAP compared to Yolov8 segmentation solely?

**Comment by akashAD98** [comment]
@mhyeonsoo 
Great you like it, Have you tried the detection model with SAM? or tried SAM automask generation model?
because im not ble to get results of more than one object.


1. For latency purposes you can check onnx model .Also SAM is saving results of each image in embedding form & its takes time, so here you can first save the all embedding of images & do operation on it,
regarding your second question

2. the whole idea is to make annotation work faster, instead of manually labeling data, also the results of SAM models are very good. so we just need to train our object detection model & pass it to SAM & it will give us Mask, 
using this mask annotation we can train our model & we can achieve performance. also in terms of performance, its depends on which model,repo & data you using.

**Comment by akashAD98** [comment]
@AouatifZ i added support for multi-image detection,you can check my .ipynb file

**Comment by mhyeonsoo** [comment]
THanks! I will take a look at the jupyter notebook.
